# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
machine:
  environment:
    PROJECT_ID: vagrant-195109
    CLUSTER_NAME: cp-cluster
    COMPUTE_ZONE: us-central1-a
    #As specified in Deployment.yml
    DEPLOYMENT_NAME: cp-react
    CONTAINER_NAME: cp-react

#Ensure that gcloud and kubectl are updated.
dependencies:
  pre:
    - sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update --version 120.0.0
    - sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update --version 120.0.0 kubectl

deployment:
    production:
        branch: master
        commands:
        # Save the string to a text file
        - echo $SERVICE_KEY > key.txt

        # Decode the Service Account
        - base64 -i key.txt -d > ${HOME}/gcloud-service-key.json

        # Authenticate CircleCI with the service account file
        - sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account ${ACCOUNT_ID} --key-file ${HOME}/gcloud-service-key.json

        # Set the default project
        - sudo /opt/google-cloud-sdk/bin/gcloud config set project $PROJECT_ID

        # Set the default container
        - sudo /opt/google-cloud-sdk/bin/gcloud --quiet config set container/cluster $CLUSTER_NAME

        # Set the compute zone
        - sudo /opt/google-cloud-sdk/bin/gcloud config set compute/zone $COMPUTE_ZONE

        # Get the cluster credentials.
        - sudo /opt/google-cloud-sdk/bin/gcloud --quiet container clusters get-credentials $CLUSTER_NAME

        # Start good old Docker
        - sudo service docker start

        # Build a Docker image and use the Github commit hash ($CIRCLE_SHA1) as the tag
        - docker build -t gcr.io/${PROJECT_ID}/react-application:$CIRCLE_SHA1 .

        # Push the Image to the GCP Container Registry
        - sudo /opt/google-cloud-sdk/bin/gcloud docker -- push gcr.io/${PROJECT_ID}/react-application:$CIRCLE_SHA1

        # Update the default image for the deployment
        - sudo /opt/google-cloud-sdk/bin/kubectl set image deployment/${DEPLOYMENT_NAME} ${CONTAINER_NAME}=gcr.io/${PROJECT_ID}/node-app:$CIRCLE_SHA1
